[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
board_build.arduino.earlephilhower.usb_manufacturer = Maximus
board_build.arduino.earlephilhower.usb_product = Maximus RGB Controller
board_build.arduino.earlephilhower.usb_pid = 0x000B
board_build.arduino.earlephilhower.usb_vid = 0x7331

build_flags = 
    -DUSE_TINYUSB

lib_deps = 
    fastled/FastLED

lib_ignore = 
    SdFat - Adafruit Fork
    SD
    SDFS